import { StyleSheet } from 'react-native';
import colors from '../../assets/colors/colors';

const localStyles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: colors.background,
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        padding: 20,
    },
    addButton: {
        backgroundColor: '#2ecc71',
        paddingVertical: 15,
        paddingHorizontal: 30,
        borderRadius: 25,
        alignItems: 'center',
        width: '80%',
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 4,
        marginTop: 15,
    },
    addButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    formContainer: {
        backgroundColor: colors.cardBackground || '#FFFFFF',
        borderRadius: 15,
        padding: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 3,
    },
    inputContainer: {
        marginBottom: 15,
    },
    label: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 5,
        color: colors.text || '#333',
    },
    input: {
        backgroundColor: colors.inputBackground || '#F4F4F8',
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderRadius: 10,
        marginBottom: 15,
        fontSize: 16,
        color: colors.inputText || '#000000',
        borderWidth: 1,
        borderColor: colors.inputBorder || '#E0E0E0',
    },
    userItem: {
        backgroundColor: colors.cardBackground || '#FFFFFF',
        padding: 15,
        marginBottom: 10,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
    },
    userName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.text || '#333',
        marginBottom: 5,
    },
    expandedUserInfo: {
        marginTop: 10,
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: colors.inputBorder || '#E0E0E0',
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    userInfoText: {
        fontSize: 14,
        color: colors.text || '#555',
        marginBottom: 3,
    },
    centered: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    searchInput: {
        backgroundColor: colors.inputBackground || '#F4F4F8',
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderRadius: 10,
        marginBottom: 5,
        fontSize: 16,
        color: colors.inputText || '#000000',
        borderWidth: 1,
        borderColor: colors.inputBorder || '#E0E0E0',
    },
    noUsersText: {
        fontSize: 16,
        color: 'white',
        textAlign: 'center',
    },
    roleFilterContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: 15,
        marginTop: 10,
        paddingHorizontal: 10,
    },
    roleButton: {
        paddingVertical: 10,
        paddingHorizontal: 5,
        borderRadius: 25,
        borderWidth: 1,
        borderColor: '#2ecc71',
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: 80,
    },
    selectedRoleButton: {
        backgroundColor: '#2ecc71',
        borderColor: '#2ecc71',
    },
    roleButtonText: {
        color: '#2ecc71',
        fontSize: 13,
        fontWeight: '600',
    },
    selectedRoleButtonText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    actionButtonsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconButton: {
        marginRight: 10,
    },
    studentGroupsButton: {
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: '#2ecc71',
        paddingVertical: 5,
        borderRadius: 25,
        alignItems: 'center',
        width: '80%',
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 4,
        marginTop: 5,
    },
    headerText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'white',
        marginBottom: 5,
    }
});

export default localStyles;